# Generated by Django 3.1.7 on 2021-03-05 05:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20210305_1016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'organization')},
        ),
    ]
