# Generated by Django 3.1.7 on 2021-03-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_for_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='password',
            field=models.TextField(blank=True),
        ),
    ]
