# Generated by Django 3.1.7 on 2021-03-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210305_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.BinaryField(blank=True),
        ),
    ]
