# Generated by Django 3.1.7 on 2021-03-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210305_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='password',
            field=models.TextField(blank=True),
        ),
    ]
