# Generated by Django 3.1.7 on 2021-03-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210305_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.item'),
            preserve_default=False,
        ),
    ]
